### ISSUE TITLE
Build doesn't seem to work anymore

### ISSUE THREAD

**Issue by acidjunk** [voorhoede/front-end-guide#47]
$ gulp build_guide
```
/Users/acidjunk/GIT/50five_theme/node_modules/karma/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^
 
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/acidjunk/GIT/50five_theme/node_modules/karma/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/acidjunk/GIT/50five_theme/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
Renes-MacBook-Pro:50five_theme acidjunk$ gulp watch
/Users/acidjunk/GIT/50five_theme/node_modules/karma/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
```
Or am I doing something wrong?

**Comment by jpsc** [comment]
What version of node/npm are you using?

**Comment by acidjunk** [comment]
node == v7.7.4
npm == 4.1.2

**Comment by jpsc** [comment]
Yes. That was never tested with those versions. It has been 2 years since this was last updated. I can try looking into that but the best way is to use an older version of node.

**Comment by acidjunk** [comment]
Can you suggest a version?

**Comment by jpsc** [comment]
`v5.12.0` works for me but I would strongly recommend not to use this. It has not been maintained for a while. You can look into [demo-viewer](https://github.com/voorhoede/demo-viewer) for a possible alternative.

**Comment by atfornes** [comment]
I had a similar issue. It is due to a deprecation of a function used at socket.io (See https://superuser.com/a/1158316/561878 and https://github.com/LearnBoost/websocket.io/issues/55)

Installing a newer karma version (which is the library that import socket.io) solved the problem for me.
